[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
remappings = [
    "create-util/=lib/snekmate/lib/create-util/contracts/",
    "erc4626-tests/=lib/snekmate/lib/erc4626-tests/",
    "forge-std/=lib/snekmate/lib/forge-std/src/",
    "murky/=lib/snekmate/lib/murky/src/",
    "openzeppelin/=lib/snekmate/lib/openzeppelin-contracts/contracts/",
    "prb/test/=lib/snekmate/lib/prb-test/src/",
    "snekmate/=lib/snekmate/src/",
    "solady/=lib/snekmate/lib/solady/src/",
    "solidity-bytes-utils/=lib/snekmate/lib/solidity-bytes-utils/contracts/",
    "solmate/=lib/snekmate/lib/solmate/src/",
    "utils/=lib/snekmate/lib/utils/",
    "@openzeppelin/contracts/=lib/snekmate/lib/openzeppelin-contracts/contracts/",
    "ds-test/=lib/snekmate/lib/solady/lib/ds-test/src/",
    "halmos-cheatcodes/=lib/halmos-cheatcodes/src/",
    "openzeppelin-contracts/=lib/snekmate/lib/openzeppelin-contracts/",
    "prb-test/=lib/snekmate/lib/prb-test/src/",
]
evm_version = "shanghai"
ffi = true


# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
